Updates multi-arch build (#179)
* Updates workflow to test multi-arch build
* Updates pkg config
* Updates validation logic in workflow

Signed-off-by: Sean Sundberg <seansund@us.ibm.com>

diff --git a/.github/workflows/verify-pr.yaml b/.github/workflows/verify-pr.yaml
--- a/.github/workflows/verify-pr.yaml
+++ b/.github/workflows/verify-pr.yaml
@@ -13,13 +13,41 @@ jobs:
 
     steps:
       - uses: actions/checkout@v3
+        with:
+          ref: ${{ github.event.release.tag_name }}
 
       - uses: actions/setup-node@v3
         with:
           node-version: '16'
 
-      - name: Verify
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v2
+
+      - name: Build
         run: |
-          npm ci
+          npm install
           npm test
           npm run build
+
+      - name: Install pkg
+        run: npm install -g pkg
+
+      - name: Build Asset
+        run: |
+          pkg -o iascable --options no-warnings .
+          ls iascable*
+
+          check_file() {
+            local name="$1"
+            if [[ ! -f "${name}" ]]; then
+              echo "File missing: ${name}" >&2
+              exit 1
+            fi
+          }
+
+          check_file iascable-linux-x64 || exit 1
+          check_file iascable-linux-arm64 || exit 1
+          check_file iascable-macos-x64 || exit 1
+          check_file iascable-macos-arm64 || exit 1
+          check_file iascable-alpine-x64 || exit 1
+          check_file iascable-alpine-arm64 || exit 1
